### ISSUE TITLE
Non-Dialog version of ember-paper-swiper

### ISSUE THREAD

**Issue by v3ss0n** [CoachLogix/ember-paper-swiper#2]
Will it be against mateterial design spec?
Would be nice if we can used a swiping ui inside any template.

**Comment by miguelcobain** [comment]
We could split this component in a non-dialog version and a normal dialog version which included the non-dialog version inside a dialog.

**Comment by miguelcobain** [comment]
@v3ss0n this was addressed in `0.0.4`. You can now use `{{#paper-swiper-inline` to display the normal swiper without the dialog.
